export const testMockData = [
    {
        "id": "1",
        "name": "Carlos Pereira",
        "document": "01021",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "ENTREGUE"
    },
    {
        "id": "2",
        "name": "Carla Souza",
        "document": "01022",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "PENDENTE"
    },
    {
        "id": "3",
        "name": "Maria Oliveira",
        "document": "01023",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "PENDENTE"
    },
    {
        "id": "4",
        "name": "João Silva",
        "document": "01024",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "ENTREGUE"
    },
    {
        "id": "5",
        "name": "Carlos Pereira",
        "document": "01025",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "ENTREGUE"
    },
    {
        "id": "6",
        "name": "Carla Souza",
        "document": "01026",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "PENDENTE"
    },
    {
        "id": "7",
        "name": "Maria Oliveira",
        "document": "01027",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "ENTREGUE"
    },
    {
        "id": "8",
        "name": "João Silva",
        "document": "01028",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "PENDENTE"
    },
    {
        "id": "9",
        "name": "Carlos Pereira",
        "document": "01029",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "PENDENTE"
    },
    {
        "id": "10",
        "name": "Carla Souza",
        "document": "01030",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "ENTREGUE"
    },
    {
        "id": "11",
        "name": "Maria Oliveira",
        "document": "01031",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "PENDENTE"
    },
    {
        "id": "12",
        "name": "João Silva",
        "document": "01032",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "PENDENTE"
    },
    {
        "id": "13",
        "name": "Carlos Pereira",
        "document": "01033",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "ENTREGUE"
    },
    {
        "id": "14",
        "name": "Carla Souza",
        "document": "01034",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "INSUCESSO"
    },
    {
        "id": "15",
        "name": "Maria Oliveira",
        "document": "01035",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "PENDENTE"
    },
    {
        "id": "16",
        "name": "João Silva",
        "document": "01036",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "ENTREGUE"
    },
    {
        "id": "17",
        "name": "Carlos Pereira",
        "document": "01037",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "PENDENTE"
    },
    {
        "id": "18",
        "name": "Carla Souza",
        "document": "01038",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "PENDENTE"
    },
    {
        "id": "19",
        "name": "Maria Oliveira",
        "document": "01039",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "ENTREGUE"
    },
    {
        "id": "20",
        "name": "João Silva",
        "document": "01040",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "ENTREGUE"
    },
    {
        "id": "21",
        "name": "Carlos Pereira",
        "document": "01041",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "PENDENTE"
    },
    {
        "id": "22",
        "name": "Carla Souza",
        "document": "01042",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "ENTREGUE"
    },
    {
        "id": "23",
        "name": "Maria Oliveira",
        "document": "01043",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "INSUCESSO"
    },
    {
        "id": "24",
        "name": "João Silva",
        "document": "01044",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "PENDENTE"
    },
    {
        "id": "25",
        "name": "Carlos Pereira",
        "document": "01045",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "ENTREGUE"
    },
    {
        "id": "26",
        "name": "Carla Souza",
        "document": "01046",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "INSUCESSO"
    },
    {
        "id": "27",
        "name": "Maria Oliveira",
        "document": "01047",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "PENDENTE"
    },
    {
        "id": "28",
        "name": "João Silva",
        "document": "01048",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "ENTREGUE"
    },
    {
        "id": "29",
        "name": "Carlos Pereira",
        "document": "01049",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "INSUCESSO"
    },
    {
        "id": "30",
        "name": "Carla Souza",
        "document": "01050",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "PENDENTE"
    },
    {
        "id": "31",
        "name": "Maria Oliveira",
        "document": "01051",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "ENTREGUE"
    },
    {
        "id": "32",
        "name": "João Silva",
        "document": "01052",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "INSUCESSO"
    },
    {
        "id": "33",
        "name": "Carlos Pereira",
        "document": "01053",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "PENDENTE"
    },
    {
        "id": "34",
        "name": "Carla Souza",
        "document": "01054",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "ENTREGUE"
    },
    {
        "id": "35",
        "name": "Maria Oliveira",
        "document": "01055",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "INSUCESSO"
    },
    {
        "id": "36",
        "name": "João Silva",
        "document": "01056",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "PENDENTE"
    },
    {
        "id": "37",
        "name": "Carlos Pereira",
        "document": "01057",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "ENTREGUE"
    },
    {
        "id": "38",
        "name": "Carla Souza",
        "document": "01058",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "INSUCESSO"
    },
    {
        "id": "39",
        "name": "Maria Oliveira",
        "document": "01059",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "PENDENTE"
    },
    {
        "id": "40",
        "name": "João Silva",
        "document": "01060",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "ENTREGUE"
    }
]


export const  arrayFilterbyNameMock = [
    {
      "id": "4",
      "name": "João Silva",
      "document": "01024",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Liberdade",
      "destinationCostumer": "Paula Silva",
      "destinationAddress": "Rua da Consolação, 123",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Centro",
      "status": "ENTREGUE"
    },
    {
      "id": "8",
      "name": "João Silva",
      "document": "01028",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Jardins",
      "destinationCostumer": "Ana Clara",
      "destinationAddress": "Rua Vergueiro, 1234",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Liberdade",
      "status": "PENDENTE"
    },
    {
      "id": "12",
      "name": "João Silva",
      "document": "01032",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Bela Vista",
      "destinationCostumer": "Carlos Lima",
      "destinationAddress": "Rua Paulista, 101",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Moema",
      "status": "PENDENTE"
    },
    {
      "id": "16",
      "name": "João Silva",
      "document": "01036",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Consolação",
      "destinationCostumer": "Pedro Lima",
      "destinationAddress": "Avenida Brasil, 1010",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Jardins",
      "status": "ENTREGUE"
    },
    {
      "id": "20",
      "name": "João Silva",
      "document": "01040",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Jardim Paulista",
      "destinationCostumer": "Ana Souza",
      "destinationAddress": "Rua Vergueiro, 567",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Consolação",
      "status": "ENTREGUE"
    },
    {
      "id": "24",
      "name": "João Silva",
      "document": "01044",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Moema",
      "destinationCostumer": "João Mendes",
      "destinationAddress": "Rua Pamplona, 567",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Jardim Paulista",
      "status": "PENDENTE"
    },
    {
      "id": "28",
      "name": "João Silva",
      "document": "01048",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Centro",
      "destinationCostumer": "Maria Souza",
      "destinationAddress": "Avenida Paulista, 456",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Bela Vista",
      "status": "ENTREGUE"
    },
    {
      "id": "32",
      "name": "João Silva",
      "document": "01052",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Liberdade",
      "destinationCostumer": "Paula Silva",
      "destinationAddress": "Rua da Consolação, 123",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Centro",
      "status": "INSUCESSO"
    },
    {
      "id": "36",
      "name": "João Silva",
      "document": "01056",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Jardins",
      "destinationCostumer": "Ana Clara",
      "destinationAddress": "Rua Vergueiro, 1234",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Liberdade",
      "status": "PENDENTE"
    },
    {
      "id": "40",
      "name": "João Silva",
      "document": "01060",
      "originCostumer": "Empresa XYZ",
      "originAddress": "Rua das Flores, 123",
      "originCity": "São Paulo",
      "originNeighborhood": "Bela Vista",
      "destinationCostumer": "Carlos Lima",
      "destinationAddress": "Rua Paulista, 101",
      "destinationCity": "São Paulo",
      "destinationNeighborhood": "Moema",
      "status": "ENTREGUE"
    }
  ]

  export const ArrayPendingMock = [
    {
        "id": "2",
        "name": "Carla Souza",
        "document": "01022",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "PENDENTE"
    },
    {
        "id": "3",
        "name": "Maria Oliveira",
        "document": "01023",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "PENDENTE"
    },
    {
        "id": "6",
        "name": "Carla Souza",
        "document": "01026",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "PENDENTE"
    },
    {
        "id": "8",
        "name": "João Silva",
        "document": "01028",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "PENDENTE"
    },
    {
        "id": "9",
        "name": "Carlos Pereira",
        "document": "01029",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "PENDENTE"
    },
    {
        "id": "11",
        "name": "Maria Oliveira",
        "document": "01031",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "PENDENTE"
    },
    {
        "id": "12",
        "name": "João Silva",
        "document": "01032",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "PENDENTE"
    },
    {
        "id": "15",
        "name": "Maria Oliveira",
        "document": "01035",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "PENDENTE"
    },
    {
        "id": "17",
        "name": "Carlos Pereira",
        "document": "01037",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "PENDENTE"
    },
    {
        "id": "18",
        "name": "Carla Souza",
        "document": "01038",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "PENDENTE"
    },
    {
        "id": "21",
        "name": "Carlos Pereira",
        "document": "01041",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "PENDENTE"
    },
    {
        "id": "24",
        "name": "João Silva",
        "document": "01044",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "PENDENTE"
    },
    {
        "id": "27",
        "name": "Maria Oliveira",
        "document": "01047",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "PENDENTE"
    },
    {
        "id": "30",
        "name": "Carla Souza",
        "document": "01050",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "PENDENTE"
    },
    {
        "id": "33",
        "name": "Carlos Pereira",
        "document": "01053",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "PENDENTE"
    },
    {
        "id": "36",
        "name": "João Silva",
        "document": "01056",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "PENDENTE"
    },
    {
        "id": "39",
        "name": "Maria Oliveira",
        "document": "01059",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "PENDENTE"
    }
]

export const arraySuccessMock = [
    {
        "id": "1",
        "name": "Carlos Pereira",
        "document": "01021",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "ENTREGUE"
    },
    {
        "id": "4",
        "name": "João Silva",
        "document": "01024",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "ENTREGUE"
    },
    {
        "id": "5",
        "name": "Carlos Pereira",
        "document": "01025",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "ENTREGUE"
    },
    {
        "id": "7",
        "name": "Maria Oliveira",
        "document": "01027",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "ENTREGUE"
    },
    {
        "id": "10",
        "name": "Carla Souza",
        "document": "01030",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "ENTREGUE"
    },
    {
        "id": "13",
        "name": "Carlos Pereira",
        "document": "01033",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "ENTREGUE"
    },
    {
        "id": "16",
        "name": "João Silva",
        "document": "01036",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "ENTREGUE"
    },
    {
        "id": "19",
        "name": "Maria Oliveira",
        "document": "01039",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "ENTREGUE"
    },
    {
        "id": "20",
        "name": "João Silva",
        "document": "01040",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "ENTREGUE"
    },
    {
        "id": "22",
        "name": "Carla Souza",
        "document": "01042",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "ENTREGUE"
    },
    {
        "id": "25",
        "name": "Carlos Pereira",
        "document": "01045",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "ENTREGUE"
    },
    {
        "id": "28",
        "name": "João Silva",
        "document": "01048",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "ENTREGUE"
    },
    {
        "id": "31",
        "name": "Maria Oliveira",
        "document": "01051",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "ENTREGUE"
    },
    {
        "id": "34",
        "name": "Carla Souza",
        "document": "01054",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardim Paulista",
        "destinationCostumer": "Ana Souza",
        "destinationAddress": "Rua Vergueiro, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Consolação",
        "status": "ENTREGUE"
    },
    {
        "id": "37",
        "name": "Carlos Pereira",
        "document": "01057",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "ENTREGUE"
    },
    {
        "id": "40",
        "name": "João Silva",
        "document": "01060",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "ENTREGUE"
    }
]

export const arrayFailureMock = [
    {
        "id": "14",
        "name": "Carla Souza",
        "document": "01034",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "INSUCESSO"
    },
    {
        "id": "23",
        "name": "Maria Oliveira",
        "document": "01043",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Consolação",
        "destinationCostumer": "Pedro Lima",
        "destinationAddress": "Avenida Brasil, 1010",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardins",
        "status": "INSUCESSO"
    },
    {
        "id": "26",
        "name": "Carla Souza",
        "document": "01046",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Bela Vista",
        "destinationCostumer": "Carlos Lima",
        "destinationAddress": "Rua Paulista, 101",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Moema",
        "status": "INSUCESSO"
    },
    {
        "id": "29",
        "name": "Carlos Pereira",
        "document": "01049",
        "originCostumer": "Empresa ABC",
        "originAddress": "Rua dos Pinheiros, 789",
        "originCity": "São Paulo",
        "originNeighborhood": "Jardins",
        "destinationCostumer": "Ana Clara",
        "destinationAddress": "Rua Vergueiro, 1234",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Liberdade",
        "status": "INSUCESSO"
    },
    {
        "id": "32",
        "name": "João Silva",
        "document": "01052",
        "originCostumer": "Empresa XYZ",
        "originAddress": "Rua das Flores, 123",
        "originCity": "São Paulo",
        "originNeighborhood": "Liberdade",
        "destinationCostumer": "Paula Silva",
        "destinationAddress": "Rua da Consolação, 123",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Centro",
        "status": "INSUCESSO"
    },
    {
        "id": "35",
        "name": "Maria Oliveira",
        "document": "01055",
        "originCostumer": "Empresa GHI",
        "originAddress": "Avenida Ibirapuera, 890",
        "originCity": "São Paulo",
        "originNeighborhood": "Centro",
        "destinationCostumer": "Maria Souza",
        "destinationAddress": "Avenida Paulista, 456",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Bela Vista",
        "status": "INSUCESSO"
    },
    {
        "id": "38",
        "name": "Carla Souza",
        "document": "01058",
        "originCostumer": "Empresa DEF",
        "originAddress": "Rua Augusta, 345",
        "originCity": "São Paulo",
        "originNeighborhood": "Moema",
        "destinationCostumer": "João Mendes",
        "destinationAddress": "Rua Pamplona, 567",
        "destinationCity": "São Paulo",
        "destinationNeighborhood": "Jardim Paulista",
        "status": "INSUCESSO"
    }
]